local ProgressionConfigs = {
    [1] = { orders = { min = 1, max = 1 }, chefs = { min = 0, max = 0 } },
    [2] = { orders = { min = 1, max = 1 }, chefs = { min = 0, max = 0 } },
    [3] = { orders = { min = 1, max = 1 }, chefs = { min = 0, max = 0 } },
    [4] = { orders = { min = 1, max = 1 }, chefs = { min = 0, max = 0 } },
    [5] = { orders = { min = 1, max = 1 }, chefs = { min = 1, max = 1 } },
    [6] = { orders = { min = 1, max = 2}, chefs = { min = 1, max = 1 } },
    [7] = { orders = { min = 1, max = 2}, chefs = { min = 1, max = 1 } },
    [8] = { orders = { min = 1, max = 2}, chefs = { min = 1, max = 1 } },
    [9] = { orders = { min = 1, max = 2}, chefs = { min = 2, max = 2 } },
    [10] = { orders = { min = 1, max = 2}, chefs = { min = 2, max = 2 } },

    [11] = { orders = { min = 2, max = 3}, chefs = { min = 2, max = 2 } },
    [12] = { orders = { min = 2, max = 3}, chefs = { min = 2, max = 2 } },
    [13] = { orders = { min = 2, max = 3}, chefs = { min = 2, max = 2 } },
    [14] = { orders = { min = 2, max = 3}, chefs = { min = 3, max = 3 } },
    [15] = { orders = { min = 2, max = 3}, chefs = { min = 3, max = 3 } },
    [16] = { orders = { min = 3, max = 4}, chefs = { min = 3, max = 3 } },
    [17] = { orders = { min = 3, max = 4}, chefs = { min = 4, max = 4 } },
    [18] = { orders = { min = 3, max = 4}, chefs = { min = 4, max = 4 } },
    [19] = { orders = { min = 3, max = 4}, chefs = { min = 4, max = 4 } },
    [20] = { orders = { min = 3, max = 4}, chefs = { min = 5, max = 5 } },

    [22] = { orders = { min = 1, max = 2 }, chefs = { min = 2, max = 3 }, chefDifficulty = "Medium" },
    [23] = { orders = { min = 2, max = 2 }, chefs = { min = 2, max = 3 }, chefDifficulty = "Medium" },
    [24] = { orders = { min = 2, max = 2 }, chefs = { min = 2, max = 3 }, chefDifficulty = "Medium" },
    [25] = { orders = { min = 2, max = 2 }, chefs = { min = 2, max = 3 }, chefDifficulty = "Medium" },
    [21] = { orders = { min = 1, max = 2 }, chefs = { min = 2, max = 3 }, chefDifficulty = "Medium" },
    [26] = { orders = { min = 2, max = 3 }, chefs = { min = 2, max = 3 }, chefDifficulty = "Medium" },
    [27] = { orders = { min = 2, max = 3 }, chefs = { min = 2, max = 3 }, chefDifficulty = "Medium" },
    [28] = { orders = { min = 2, max = 3 }, chefs = { min = 2, max = 3 }, chefDifficulty = "Medium" },
    [29] = { orders = { min = 2, max = 3 }, chefs = { min = 2, max = 3 }, chefDifficulty = "Medium" },
    [30] = { orders = { min = 2, max = 3 }, chefs = { min = 2, max = 3 }, chefDifficulty = "Medium" },

    [31] = { orders = { min = 3, max = 4 }, chefs = { min = 3, max = 4 }, chefDifficulty = "Medium" },
    [32] = { orders = { min = 3, max = 4 }, chefs = { min = 3, max = 4 }, chefDifficulty = "Medium" },
    [33] = { orders = { min = 3, max = 4 }, chefs = { min = 3, max = 4 }, chefDifficulty = "Medium" },
    [34] = { orders = { min = 3, max = 4 }, chefs = { min = 3, max = 4 }, chefDifficulty = "Medium" },
    [35] = { orders = { min = 3, max = 4 }, chefs = { min = 3, max = 4 }, chefDifficulty = "Medium" },
    [36] = { orders = { min = 4, max = 5 }, chefs = { min = 3, max = 4 }, chefDifficulty = "Medium" },
    [37] = { orders = { min = 4, max = 5 }, chefs = { min = 3, max = 4 }, chefDifficulty = "Medium" },
    [38] = { orders = { min = 4, max = 5 }, chefs = { min = 3, max = 4 }, chefDifficulty = "Medium" },
    [39] = { orders = { min = 4, max = 5 }, chefs = { min = 3, max = 4 }, chefDifficulty = "Medium" },
    [40] = { orders = { min = 4, max = 5 }, chefs = { min = 3, max = 4 }, chefDifficulty = "Medium" },

    [41] = { orders = { min = 5, max = 6 }, chefs = { min = 4, max = 5 }, chefDifficulty = "Medium" },
    [42] = { orders = { min = 5, max = 6 }, chefs = { min = 4, max = 5 }, chefDifficulty = "Medium" },
    [43] = { orders = { min = 5, max = 6 }, chefs = { min = 4, max = 5 }, chefDifficulty = "Medium" },
    [44] = { orders = { min = 5, max = 6 }, chefs = { min = 4, max = 5 }, chefDifficulty = "Medium" },
    [45] = { orders = { min = 5, max = 6 }, chefs = { min = 4, max = 5 }, chefDifficulty = "Medium" },
    [46] = { orders = { min = 5, max = 6 }, chefs = { min = 4, max = 5 }, chefDifficulty = "Medium" },
    [47] = { orders = { min = 6, max = 7 }, chefs = { min = 4, max = 5 }, chefDifficulty = "Medium" },
    [48] = { orders = { min = 6, max = 7 }, chefs = { min = 4, max = 5 }, chefDifficulty = "Medium" },
    [49] = { orders = { min = 6, max = 7 }, chefs = { min = 4, max = 5 }, chefDifficulty = "Medium" },
    [50] = { orders = { min = 6, max = 7 }, chefs = { min = 4, max = 5 }, chefDifficulty = "Medium" },

    [51] = { orders = { min = 7, max = 8 }, chefs = { min = 5, max = 7 }, chefDifficulty = "Medium" },
    [52] = { orders = { min = 7, max = 8 }, chefs = { min = 5, max = 7 }, chefDifficulty = "Medium" },
    [53] = { orders = { min = 7, max = 8 }, chefs = { min = 5, max = 7 }, chefDifficulty = "Medium" },
    [54] = { orders = { min = 7, max = 8 }, chefs = { min = 5, max = 7 }, chefDifficulty = "Medium" },
    [55] = { orders = { min = 7, max = 8 }, chefs = { min = 5, max = 7 }, chefDifficulty = "Medium" },
    [56] = { orders = { min = 8, max = 9 }, chefs = { min = 5, max = 7 }, chefDifficulty = "Medium" },
    [57] = { orders = { min = 8, max = 9 }, chefs = { min = 5, max = 7 }, chefDifficulty = "Medium" },
    [58] = { orders = { min = 8, max = 9 }, chefs = { min = 5, max = 7 }, chefDifficulty = "Medium" },
    [59] = { orders = { min = 8, max = 9 }, chefs = { min = 5, max = 7 }, chefDifficulty = "Medium" },
    [60] = { orders = { min = 8, max = 9 }, chefs = { min = 5, max = 7 }, chefDifficulty = "Medium" },

    [61] = { orders = { min = 1, max = 3 }, chefs = { min = 1, max = 3 }, chefDifficulty = "Hard" },
    [62] = { orders = { min = 1, max = 3 }, chefs = { min = 1, max = 3 }, chefDifficulty = "Hard" },
    [63] = { orders = { min = 1, max = 3 }, chefs = { min = 1, max = 3 }, chefDifficulty = "Hard" },
    [64] = { orders = { min = 2, max = 3 }, chefs = { min = 1, max = 3 }, chefDifficulty = "Hard" },
    [65] = { orders = { min = 2, max = 3 }, chefs = { min = 1, max = 3 }, chefDifficulty = "Hard" },
    [66] = { orders = { min = 2, max = 3 }, chefs = { min = 1, max = 3 }, chefDifficulty = "Hard" },
    [67] = { orders = { min = 3, max = 4 }, chefs = { min = 1, max = 3 }, chefDifficulty = "Hard" },
    [68] = { orders = { min = 3, max = 4 }, chefs = { min = 1, max = 3 }, chefDifficulty = "Hard" },
    [69] = { orders = { min = 3, max = 4 }, chefs = { min = 1, max = 3 }, chefDifficulty = "Hard" },
    [70] = { orders = { min = 3, max = 4 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },

    [71] = { orders = { min = 3, max = 4 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },
    [72] = { orders = { min = 3, max = 4 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },
    [73] = { orders = { min = 3, max = 4 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },
    [74] = { orders = { min = 3, max = 4 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },
    [75] = { orders = { min = 4, max = 5 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },
    [76] = { orders = { min = 4, max = 5 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },
    [77] = { orders = { min = 4, max = 5 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },
    [78] = { orders = { min = 4, max = 5 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },
    [79] = { orders = { min = 5, max = 6 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },
    [80] = { orders = { min = 5, max = 6 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },

    [81] = { orders = { min = 6, max = 7 }, chefs = { min = 4, max = 7 }, chefDifficulty = "Hard" },
    [82] = { orders = { min = 6, max = 7 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [83] = { orders = { min = 6, max = 7 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [84] = { orders = { min = 6, max = 7 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [85] = { orders = { min = 6, max = 7 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [86] = { orders = { min = 7, max = 8 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [87] = { orders = { min = 7, max = 8 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [88] = { orders = { min = 7, max = 8 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [89] = { orders = { min = 7, max = 8 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [90] = { orders = { min = 7, max = 8 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },

    [91] = { orders = { min = 8, max = 9 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [92] = { orders = { min = 8, max = 9 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [93] = { orders = { min = 8, max = 9 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [94] = { orders = { min = 8, max = 9 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [95] = { orders = { min = 8, max = 9 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [96] = { orders = { min = 9, max = 10 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [97] = { orders = { min = 9, max = 10 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [98] = { orders = { min = 9, max = 10 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [99] = { orders = { min = 9, max = 10 }, chefs = { min = 8, max = 13 }, chefDifficulty = "Hard" },
    [100] = { orders = 10, chefs = { min = 14, max = 15 }, chefDifficulty = "Hard" },
}

return ProgressionConfigs;